#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

if [ -e "/boot/efi/verity/rootfs.uuid" ]; then
        UUID=$(cat /boot/efi/verity/rootfs.uuid)
        VERITYDATADEV=/dev/disk/by-uuid/${UUID}
        echo "VERITYDATADEV $VERITYDATADEV"
fi

if [ -e "/boot/efi/verity/verityfs.uuid" ]; then
        UUID=$(cat /boot/efi/verity/verityfs.uuid)
        VERITYTREEDEV=/dev/disk/by-uuid/${UUID}
        echo "VERITYTREEDEV $VERITYTREEDEV"
fi

if [ -e "/boot/efi/verity/rootfs.hash" ]; then
        VERITYHASH=$(cat /boot/efi/verity/rootfs.hash)
        echo "VERITYHASH $VERITYHASH"
fi

if [ -e "/boot/efi/verity/verity.name" ]; then
        VERITYNAME=$(cat /boot/efi/verity/verity.name)
        echo "VERITYNAME $VERITYNAME"
fi

SETTINGS_COUNT=0
if [ -n "$VERITYDATADEV" ]; then
    SETTINGS_COUNT=$((SETTINGS_COUNT+1))
fi
if [ -n "$VERITYTREEDEV" ]; then
    SETTINGS_COUNT=$((SETTINGS_COUNT+1))
fi
if [ -n "$VERITYHASH" ]; then
    SETTINGS_COUNT=$((SETTINGS_COUNT+1))
fi
if [ -n "$VERITYNAME" ]; then
    SETTINGS_COUNT=$((SETTINGS_COUNT+1))
fi

if [ $SETTINGS_COUNT -eq 0 ]; then
    /scripts/measure-event "VERITY_BYPASS"
    echo "No verity settings"
    exit 0
fi

if [ $SETTINGS_COUNT -ne 4 ]; then
    /scripts/measure-event "VERITY_FAILURE"
    echo "Verity settings incorrect! Must supply veritydata, veritytree, verityhash, verityname"
    exit 1
fi

echo "Opening verity device"
/scripts/measure-event "VERITY_HASH: $VERITYHASH"

ret=0
veritysetup -v open "$VERITYDATADEV" "$VERITYNAME" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?

if [ $ret -ne 0 ]; then
    echo "veritysetup failed!"
    /scripts/measure-event "VERITY_FAILURE"
else
    echo "Verity device created!"
    /scripts/measure-event "VERITY_SUCCESS"
fi
