#!/bin/bash

set -e

az sig create --resource-group $AZURE_RESOURCE_GROUP \
              --gallery-name $AZURE_GALLERY_NAME

az sig image-definition create --resource-group $AZURE_RESOURCE_GROUP \
                               --gallery-name $AZURE_GALLERY_NAME \
                               --gallery-image-definition $AZURE_IMAGE_DEFINITION \
                               --os-state Specialized \
                               --os-type Linux \
                               --features SecurityType=TrustedLaunch \
                               --publisher DemoPublisher \
                               --offer DemoOffer \
                               --sku DemoSku
