#!/bin/bash

set -e

VM_NAME=$1
VM_IMAGE=$2
VM_USER="${AZURE_USER_NAME:-azureuser}"

if ! [ -f ~/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
fi

az vm create --resource-group $AZURE_RESOURCE_GROUP \
             --name $VM_NAME \
             --image $VM_IMAGE \
             --size Standard_D4ds_v5 \
             --admin-username $VM_USER \
             --ssh-key-value ~/.ssh/id_rsa.pub \
             --security-type TrustedLaunch \
             --nic-delete-option delete \
             --os-disk-delete-option detach \
             --patch-mode ImageDefault
