#!/bin/bash

set -e

VM_NAME=$1
VM_USER="${AZURE_USER_NAME:-azureuser}"

if ! [ -f ~/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
fi

az account set --subscription $AZURE_SUBSCRIPTION_ID
az group create --resource-group $AZURE_RESOURCE_GROUP --location $AZURE_LOCATION

az vm create --resource-group $AZURE_RESOURCE_GROUP \
             --name $VM_NAME \
             --image Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest \
             --size Standard_D4ds_v5 \
             --admin-username $VM_USER \
             --ssh-key-value ~/.ssh/id_rsa.pub \
             --security-type TrustedLaunch \
             --nic-delete-option delete \
             --os-disk-delete-option detach \
             --patch-mode ImageDefault
