# yamllint disable rule:line-length
name: Test for BuildEnv L1 container build

on:
  push:
    branches:
      - main
    paths:
      - 'build-container/**'

permissions:
  id-token: write
  attestations: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build docker container
        id: build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: "."
          file: "build-container/test-buildenv.dockerfile"
          tags: "test_l1:latest"

      - name: Generate SLSA Provenance
        id: slsa
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: "test_l1"
          subject-digest: ${{ steps.build.outputs.digest }}
