# yamllint disable rule:line-length
name: Test for BuildEnv L2 container build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'build-container/**'

permissions:
  id-token: write
  attestations: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v5
        with:
          go-version: 1.24.x

      - name: Install scai-gen CLI tools
        shell: bash
        run: |
          go install github.com/in-toto/scai-demos/scai-gen@latest

      # Per BuildEnv L2, MUST automatically generate and distribute
      # signed reference values for the bootloader or equivalent, guest
      # kernel, build platform client, build executor, and root filesystem.
      - name: Attest container reference values
        id: ref-values
        uses: ./.github/actions/attest-ref-values
        with:
          reference-path: 'build-container/*'

      - name: Build docker container
        id: build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: "."
          file: "build-container/test-buildenv.dockerfile"
          tags: "test_l2:latest"

      - name: Generate SLSA Provenance
        id: slsa
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: "test_l2"
          subject-digest: ${{ steps.build.outputs.digest }}
